WARNING: Could not find any nv files on this host!
/ext3/miniconda3/lib/python3.9/site-packages/numba/core/cpu.py:97: UserWarning: Numba extension module 'sparse._numba_extension' failed to load due to 'ContextualVersionConflict((numpy 1.22.4 (/ext3/miniconda3/lib/python3.9/site-packages), Requirement.parse('numpy<1.22,>=1.18'), {'numba'}))'.
  numba.core.entrypoints.init_all()
PREPROCESS CASE lat_-57_-42_lon_23_37/
2022-10-08 22:57:25.204454
T,S,U,V,W FROM LLC4320
2022-10-08 22:57:25.204491
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/indexing.py:1380: PerformanceWarning: Slicing is producing a large chunk. To accept the large
chunk and silence this warning, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': False}):
    ...     array[indexer]

To avoid creating the large chunks, set the option
    >>> with dask.config.set(**{'array.slicing.split_large_chunks': True}):
    ...     array[indexer]
  value = value[(slice(None),) * axis + (subkey,)]
CALCULATE B
2022-10-09 05:02:50.609195
SAVE SNAPSHOT: B,U,V,W
2022-10-09 05:20:50.324686
SAVE SNAPSHOT: MLD
2022-10-09 05:21:43.449854
FILTER
2022-10-09 05:21:44.566262
Traceback (most recent call last):
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 391, in _info
    await _file_info(
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 772, in _file_info
    r.raise_for_status()
  File "/home/ab10313/.local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_4320/grid/YC.data')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ab10313/submeso_ML/preprocess_code/preprocess_llc4320_save_lat_-57_-42_lon_23_37_debug.py", line 243, in <module>
    Wm = filter_factor24.apply(W.where(wet_mask), dims=['i', 'j'])
  File "/home/ab10313/.local/lib/python3.9/site-packages/gcm_filters/filter.py", line 479, in apply
    return self._apply_to_dataarray(ds, dims=dims)
  File "/home/ab10313/.local/lib/python3.9/site-packages/gcm_filters/filter.py", line 488, in _apply_to_dataarray
    field_smooth = xr.apply_ufunc(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/computation.py", line 1204, in apply_ufunc
    return apply_dataarray_vfunc(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/computation.py", line 310, in apply_dataarray_vfunc
    result_coords, result_indexes = build_output_coords_and_indexes(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/computation.py", line 261, in build_output_coords_and_indexes
    merged_vars, merged_indexes = merge_coordinates_without_align(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/merge.py", line 420, in merge_coordinates_without_align
    merged_coords, merged_indexes = merge_collected(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/merge.py", line 302, in merge_collected
    merged_vars[name] = unique_variable(
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/merge.py", line 151, in unique_variable
    equals = getattr(out, compat)(var)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 1999, in broadcast_equals
    return self.equals(other, equiv=equiv)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/variable.py", line 1983, in equals
    self._data is other._data or equiv(self.data, other.data)
  File "/ext3/miniconda3/lib/python3.9/site-packages/xarray/core/duck_array_ops.py", line 242, in array_equiv
    return bool(flag_array.all())
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/array/core.py", line 1771, in __bool__
    return bool(self.compute())
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/base.py", line 290, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/base.py", line 573, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/threaded.py", line 81, in get
    results = get_async(
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 506, in get_async
    raise_exception(exc, tb)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 314, in reraise
    raise exc
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/local.py", line 219, in execute_task
    result = _execute_task(task, data)
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/ext3/miniconda3/lib/python3.9/site-packages/dask/core.py", line 119, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/home/ab10313/.local/lib/python3.9/site-packages/xmitgcm/llcreader/llcmodel.py", line 459, in _get_facet_chunk
    file = fs.open(path)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/spec.py", line 1034, in open
    f = self._open(
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 340, in _open
    size = size or self.info(path, **kwargs)["size"]
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 111, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 96, in sync
    raise return_result
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/asyn.py", line 53, in _runner
    result[0] = await coro
  File "/ext3/miniconda3/lib/python3.9/site-packages/fsspec/implementations/http.py", line 404, in _info
    raise FileNotFoundError(url) from exc
FileNotFoundError: https://data.nas.nasa.gov/ecco/download_data.php?file=/eccodata/llc_4320/grid/YC.data
